use crate::sub_page::SUB_PAGE_MESSAGES_AMOUNT;

pub const MESSAGES_PER_CLUSTER: usize = 100_000_000;

pub const SUB_PAGES_PER_CLUSTER: usize = MESSAGES_PER_CLUSTER / SUB_PAGE_MESSAGES_AMOUNT;

pub const COMPRESSED_CLUSTER_TOC: usize = SUB_PAGES_PER_CLUSTER * 8;

pub const COMPRESSED_CLUSTER_TOC_IN_PAGES: usize = COMPRESSED_CLUSTER_TOC / 512 + 1;
