pub const MESSAGES_PER_CLUSTER: usize = 100_000_000;

pub const MESSAGES_PER_COMPRESSED_PAGE: usize = 1_000;

pub const PAGES_PER_CLUSTER: usize = MESSAGES_PER_CLUSTER / MESSAGES_PER_COMPRESSED_PAGE;

pub const COMPRESSED_CLUSTER_TOC: usize = PAGES_PER_CLUSTER * 8;

pub const COMPRESSED_CLUSTER_TOC_IN_PAGES: usize = COMPRESSED_CLUSTER_TOC / 512 + 1;
