[package]
name = "my-sb-persistence"
version = "1.1.1"
authors = ["Andrey <amigin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-azure-storage-sdk = { git = "https://github.com/MyJetTools/my-azure-storage.git" }
my-azure-page-blob = { git = "https://github.com/MyJetTools/my-azure-page-blob.git" }
tonic = { version = "0.5.0", features = ["tls", "tls-roots", "prost"] }

hyper = { version = "0.14.7", features = ["full"] }
tokio = { version = "*", features = ["full"] }
tokio-util = "*"
chrono = "0.4.19"
lazy_static = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
serde_yaml = "*"
base64 = "*"
zip = "*"
md5 = "*"
anyhow = "1.0.40"
futures-core = "*"
prost = "0.8.0"
prost-types = "0.8.0"
tokio-stream = "*"
async-trait = "*"
futures-util = "*"
tokio-signal = "*"
signal-hook = "*"
rand = "*"
sysinfo = "*"
prometheus = "0.12.0"

[build-dependencies]
tonic-build = { version = "0.5.0", features = ["prost"] }
