name: Test commit

on:
  push:
    branches: "*"
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1       
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Test Build      
        run: |
          cargo test
